### PR TITLE
Fixed bug and added deleteAllTimewindows

### PR DESCRIPTION
**Pull request by CrEaK**
Hey,
its me again. With this pull request I fixed/added three things:
1. I fixed the timestamp generation for nello-events:
image
There was a wrong null check that I fixed with 6cce33b
2. I changed the generation of the indexedTimeWindows-object. I think this is a cleaner way to generate the comma-sperated string. I needed this change for change 3. Included in 49519c9
3. I added a new button to delete all timewindows that are in the indexedTimeWindows-object. First I wanted to use the api function directly, but there was a problem with the callbacks and there was no way to know if when the last callback is coming back to update the objects. So I simply indexedTimeWindows so I know the number of time windows and have the corresponding id on hand for log entries. 

Feel free to give feedback on my changes :-) 

Thanks!

### CODE REVIEW

**Review by Zefau — CHANGES_REQUESTED** [review]
Hi there. Thanks again for your effort and contribution. Looks good.

The indexArray is a good idea. I was wondering though if we could define it globally (somewhere around line 15) and use it to retrieve all windows instead of retrieving them from the state (replacing line 331 with indexArray.forEach) ?

Thinking this further it actually could be an object instead, where the time window ID is the key. With this we could also replace getState (#L292 and https://github.com/Zefau/ioBroker.nello/blob/master/main.js#L296) when deleting a single time window.

What do you think?

**Comment by CrEaK** [comment]
Hi, 
sounds good to me. I will look into it. 
One question though: With object you mean something like indexMap[timewindowID] =  < timewindow-object > ? In this case I dont get how we can get rid of the getState? timeWindows.< timewindowID >.deleteTimeWindow triggers the delete and what comes then?

**Comment by CrEaK** [comment]
May have a look into my recent commit. What do you think?

**Comment by Zefau** [comment]
You're quick ;-) And you're right, the object is necessary to actually retrieve and know the specific time window that the action has been applied on. I was too euphoric with the idea of the array :-)

I thought this through a bit more. I would probably be best to have an object for all locations with the location_id as key and `address` and time windows (`tw`) as object values, like

```
var locations = {
     1: {
       'address': {..},
       'tw': {
           1: {..},
           2: {..}
   }
}
```

with this a lot of code within `adapter.on('stateChange', function(id, state)` can be reduced.

Give me feedback if you want to implement the change, otherwise I will merge your pull request and implement it myself, that's ok.

Thanks again for the contribution and the helpful discussions.

**Comment by CrEaK** [comment]
I try my best :)
Yeah, thats sounds reasonable to me. Good idea! I will look into this on the weekend and will implement the changes into this pull request. 

No problem, Im happy that I can finally drop my own hacky python webservice for handling nello timewindows :D

Have a nice Weekend!

**Comment by CrEaK** [comment]
Found the time to work on this 👍 

Can you have a look?

**Comment by Zefau** [comment]
Travis check failed. Operator "!=x" is unknown in row 494
```
var feed = state !=x undefined && state !== null && state.val !== '' ? JSON.parse(state.val) : [];
```

Please change commit _Removed unnecessary log messages_ again and change adapter.log.info to adapter.log.debug. For support purposes it is always handy to have the log info.

I will merge after these changes

Thanks again and kind regards,
Zefau

**Comment by CrEaK** [comment]
Added the debug logs and removed the typo. Now everything should work as it expected 👍 

Kind regards!

**Review by Zefau — APPROVED** [review]

**Comment by Zefau** [comment]
Thanks

**Pull request merged**
